<?php

/**
 * @file
 * Allows SSH keys to be associated with entities.
 */

/**
 * Implements hook_theme().
 */
function sshkey_theme($existing, $type, $theme, $path) {
  $info['sshkey_fingerprint'] = [
    'variables' => ['key' => NULL],
  ];
  return $info;
}

/**
 * Theme callback to output a formatted SSH key fingerprint.
 */
function theme_sshkey_fingerprint($variables) {
  $key = $variables['key'];
  $chunks = str_split($key->fingerprint, 2);
  return implode(':', $chunks);
}
