field.storage_settings.sshkey_default:
  type: mapping
  label: SSH Key storage settings
  mapping:
    foo:
      type: string
      label: Foo

field.field_settings.sshkey_default:
  type: mapping
  label: SSH Key field settings
  mapping:
    algorithm:
      type: mapping
      label: Algorithm
      mapping:
        ssh-rsa:
          type: boolean
          label: ssh-rsa
        ssh-dss:
          type: boolean
          label: ssh-dss
        ssh-ed25519:
          type: boolean
          label: ssh-ed25519

field.value.sshkey_default:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value
    fingerprint:
      type: label
      label: Fingerprint
    name:
      type: label
      label: Name

field.formatter.settings.sshkey_fingerprint:
  type: mapping
  label: Fingerprint formatter settings
  mapping:
    prefix:
      type: string
      label: Prefix
    suffix:
      type: string
      label: Suffix

field.widget.settings.sshkey_textarea:
  type: mapping
  label: Textarea widget settings
  mapping:
    size:
      type: integer
      label: size
    placeholder:
      type: string
      label: Placeholder
    prefix:
      type: string
      label: Prefix
    suffix:
      type: string
      label: Suffix

field.formatter.settings.sshkey_name:
  type: mapping
  label: Name formatter settings
  mapping:
    prefix:
      type: string
      label: Prefix
    suffix:
      type: string
      label: Suffix
